version: '3.8'
services:
  media-subscribe:
    image: klaxonz/media-subscribe:latest
    container_name: media-subscribe
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=ms123456
      - MYSQL_DATABASE=media_subscribe
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./downloads:/app/downloads
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy

  redis:
    image: redis:latest
    container_name: media-subscribe-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis/config:/usr/local/etc/redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 2s
      retries: 5

  mysql:
    image: mysql:latest
    container_name: media-subscribe-mysql
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ms123456
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER --password=$$MYSQL_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 3
